#!/bin/bash

#SBATCH --job-name=template_job       # Job name
#SBATCH --mail-type=END,FAIL          # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=template@mail.com # Where to send mail
#SBATCH --ntasks=1                    # Run on a single CPU (for more CPUs, use 'srun' --> OpenMPI)
#SBATCH --ntasks-per-node=1           # If using multiple CPUs per node
#SBATCH --nodes=1                     # Number of nodes to use
#SBATCH --cpus-per-task=1             # Single-threaded
#SBATCH --mem-per-cpu=1gb             # Memory per CPU request
#SBATCH --partition=gpu_partition     # Partition to be used
#SBATCH --gpus=4                      # Number of GPUs
#SBATCH --time=00:05:00               # Time limit days-hrs:min:sec
#SBATCH --output=template_out.log     # Standard output log
#SBATCH --error=template_err.log      # Standard error log

pwd; hostname; date

module load python

echo "Running template slurm job "

python /src/hello_world_module.py

date