name: Pytest on Push

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11.0
      uses: actions/setup-python@v3
      with:
        python-version: 3.11.0
    - name: Add conda to system path
      run: |
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        apt update && apt install sudo
        sudo apt-get update && sudo apt-get install cmake libopenmpi-dev python3-dev zlib1g-dev
        pip install -r requirements.txt
    - name: Test with pytest
      run: |
        conda install pytest
        pytest test/
